import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Footer from '@/components/Footer';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <body className="bg-[url('/hero.jpg')] bg-cover bg-black bg-blend-color bg-opacity-[0.97] bg-no-repeat bg-center bg-fixed">
          <main className='relative flex flex-col min-h-screen h-screen'>
            <div className='flex-grow flex-1 '>{children}</div>
            <Footer />
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
