import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Footer from '@/components/Footer';
import { ClerkProvider } from '@clerk/nextjs';
import { dark, neobrutalism } from '@clerk/themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ClerkProvider
        appearance={{
          variables: {
            colorPrimary: '#f43f5e',
            fontSize: '1rem',
          },
        }}
      >
        <body className='bg-gray-100'>
          <main className='relative flex flex-col min-h-screen h-screen '>
            <div className='flex-grow flex-1 '>{children}</div>
            <Footer />
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
